We simulate a star network with three nodes.

In [9]:
import numpy as np

############################
# Parameter Initialization #
############################
### graph parameters ###
# number of nodes
n = 3 

# adjacency matrix
G = np.array( 
    [[0, 1, 1],
     [1, 0, 0],
     [1, 0, 0]]
)

# node degrees
d = np.sum(G, axis = 1)

### outcome model parameters ###
# treatment space
treatments = [0, 1]

# model intercept and slopes
alpha = 2
beta = -2
gamma = 1
eta = 0.5

# noise std
noise_std = 1

# confounder mean and std
confd_mean = 0.5
confd_std = 2

### other parameters ###
# time horizon
T = 100

# history of observed outcome, assigned treatments, and exposure mapping
obs_outs = np.zeros((T, n))
assign_treats = np.zeros((T, n))
exp_map = np.zeros((T, n))

In [10]:
###################
# Data Generation #
###################

rng = np.random.default_rng(123)

for t in range(T):

    # generate assigned treatments
    Z_t = rng.choice(treatments, size = n)
    assign_treats[t] = Z_t

    # generate observed confounder 
    S_t = rng.normal(confd_mean, confd_std, size = n)

    # compute exposure mapping
    if (t == 0):
        V_t = G @ obs_outs[0] / d
    else:
        V_t = G @ obs_outs[t - 1] / d
    exp_map[t] = V_t

    # generate random noise
    eps_t = rng.normal(0, noise_std, size = n)

    # compute the observed outcome
    obs_outs[t] = alpha + beta * Z_t + gamma * V_t + eta * S_t + eps_t
    


In [11]:
obs_outs

array([[  4.11502905,  -0.19248923,   1.71218312],
       [  3.87962393,   3.7911067 ,   3.83936807],
       [  3.19779687,   4.64575052,   8.00902346],
       [  8.40618725,   5.69443982,   4.73481341],
       [  6.85523598,   7.34402455,  10.04770114],
       [ 10.08427995,   7.67688821,   7.16987651],
       [  7.31320518,  14.65223979,  11.64437092],
       [ 13.42856789,   9.19610451,   9.68542103],
       [ 10.68703889,  13.6836831 ,  14.72719309],
       [ 13.53210563,  11.59817448,  11.45154611],
       [ 13.6543448 ,  12.54813515,  15.26122785],
       [ 15.51311131,  12.68271259,  14.98350782],
       [ 17.16893027,  17.22966504,  15.02188523],
       [ 14.68631887,  19.9033171 ,  19.97198996],
       [ 21.40306069,  16.43320629,  18.58772491],
       [ 20.49781125,  18.08136391,  22.36997552],
       [ 20.37341501,  20.2067123 ,  23.87129645],
       [ 22.00387444,  26.03827699,  19.61250645],
       [ 26.14622989,  22.78386737,  25.1005553 ],
       [ 27.32105003,  25.92046

In [13]:
assign_treats

array([[0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 0.],
       [1., 0., 1.],
       [1., 1., 1.],
       [1., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [1., 1., 1.],
       [0., 1., 0.],
       [1., 1., 0.],
       [0., 1., 1.],
       [1., 1., 0.],
       [1., 1., 1.],
       [0., 1., 0.],
       [1., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.],
       [0., 1., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 1., 1.],
       [0., 1., 0.],
       [1., 1., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 1.],
       [0., 0., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0

In [12]:
exp_map

array([[  0.        ,   0.        ,   0.        ],
       [  0.75984695,   4.11502905,   4.11502905],
       [  3.81523738,   3.87962393,   3.87962393],
       [  6.32738699,   3.19779687,   3.19779687],
       [  5.21462661,   8.40618725,   8.40618725],
       [  8.69586285,   6.85523598,   6.85523598],
       [  7.42338236,  10.08427995,  10.08427995],
       [ 13.14830536,   7.31320518,   7.31320518],
       [  9.44076277,  13.42856789,  13.42856789],
       [ 14.20543809,  10.68703889,  10.68703889],
       [ 11.5248603 ,  13.53210563,  13.53210563],
       [ 13.9046815 ,  13.6543448 ,  13.6543448 ],
       [ 13.83311021,  15.51311131,  15.51311131],
       [ 16.12577514,  17.16893027,  17.16893027],
       [ 19.93765353,  14.68631887,  14.68631887],
       [ 17.5104656 ,  21.40306069,  21.40306069],
       [ 20.22566971,  20.49781125,  20.49781125],
       [ 22.03900437,  20.37341501,  20.37341501],
       [ 22.82539172,  22.00387444,  22.00387444],
       [ 23.94221133,  26.14622